import { Product, Review, BlogPost } from "./types";

// --- BIEN-ÊTRE (23 Produits) ---
export const WELLNESS_PRODUCTS: Product[] = [
  {
    id: "w1",
    name: "Huile CBD Sommeil",
    category: "Huiles",
    price: 49.9,
    image: "/images/products/bien_etre/Gemini_Generated_Image_ut6cl2ut6cl2ut6c.webp",
    tags: ["Sommeil"],
    universe: "wellness",
    stock: 50,
    molecule: "CBD",
    origin: "france",
    vibe: "Apaisement profond pour une nuit sans interruption.",
    profil: "Synergie CBD/CBN boostée à la Mélatonine naturelle.",
    gout: "Douces notes de Verveine, infusion réconfortante.",
    capacity: "10ml",
    concentrationDisplay: "10%",
    metaTitle: "Huile CBD Sommeil Profond | Naturel & Bio | Gardenz",
    metaDescription:
      "Retrouvez un sommeil réparateur avec notre Huile CBD Sommeil. Formule Bio, spectre complet, effet rapide. Livraison 24h offerte dès 60€.",
    shortDescription:
      "La solution naturelle pour des nuits paisibles. Notre formule exclusive combine CBD Full Spectrum et mélatonine pour un endormissement rapide et un réveil sans somnolence.",
    benefits: [
      "Endormissement en moins de 30 min",
      "Aucune somnolence au réveil",
      "Formule 100% Naturelle & Bio",
    ],
    composition: [
      "Huile de graines de chanvre Bio",
      "Extrait de chanvre Full Spectrum (CBD 10%, CBN 2%)",
      "Mélatonine naturelle",
      "Arôme naturel de Verveine",
    ],
    usageTips:
      "Agitez avant emploi. Déposez 3 gouttes sous la langue 30 minutes avant le coucher. Gardez en bouche 60 secondes avant d'avaler.",
    checklist: [
      "Coupez les écrans 30 min avant utilisation",
      "Prenez 3 gouttes sous la langue",
      "Lisez quelques pages d'un livre",
      "Extinction des feux",
    ],
    dosage: { base: "3", max: "9", unit: "gouttes" },
    labCertificate: "/certificates/w1-analysis.pdf",
    images: [
      "/images/products/bien_etre/huile-cbd-sommeil.webp",
      "/images/products/bien_etre/serum-cbd-visage.webp",
    ],
    video: "/medias/video.mp4",
    seoContent: {
      heading: "Pourquoi cette Huile CBD Sommeil est unique ?",
      subheading: "Une synergie botanique puissante validée par la science",
      description:
        "Contrairement aux huiles CBD classiques, notre formulation **Sommeil Profond** utilise l'effet d'entourage pour maximiser l'efficacité. Le mariage du **CBN (Cannabinol)**, connu pour ses vertus sédatives, et de la **Mélatonine**, hormone naturelle du sommeil, crée une réponse biologique immédiate sans accoutumance.",
      features: [
        {
          title: "Sommeil Réparateur",
          content:
            "Favorise l'accès aux phases de sommeil profond grâce au CBN.",
        },
        {
          title: "Endormissement Rapide",
          content: "La mélatonine réduit le temps de latence avant le sommeil.",
        },
        {
          title: "Réveil Tonique",
          content:
            "Aucun effet 'tête dans le brouillard' au réveil, contrairement aux somnifères chimiques.",
        },
      ],
      expertQuote: {
        author: "Dr. Sophie M.",
        role: "Pharmacienne & Naturopathe",
        text: "Cette formulation est l'une des plus abouties du marché. Le dosage précis en mélatonine couplé au spectre complet du chanvre offre une alternative naturelle crédible aux hypnotiques légers.",
      },
      scientificSources: [
        {
          title: "Étude sur l'effet du CBD sur le cycle veille-sommeil (2019)",
          url: "https://pubmed.ncbi.nlm.nih.gov/",
        },
        {
          title:
            "Rôle du Système Endocannabinoïde dans la régulation circadienne",
          url: "https://nature.com/articles/",
        },
      ],
    },
  },
  {
    id: "w4",
    name: "Huile CBN Nuit Profonde",
    category: "Huiles",
    price: 59.9,
    image: "/images/products/bien_etre/Whisk_wqwm3ymmxy2y0mmntmzn4gtl2qwz00yyhnjytkd.webp",
    tags: ["Sommeil"],
    universe: "wellness",
    stock: 15,
    molecule: "CBN",
    metaTitle: "Huile CBN Nuit Profonde 10ml | Sommeil Réparateur - Gardenz",
    metaDescription:
      "Découvrez la puissance du CBN pour des nuits complètes. Idéal pour les insomnies tenaces. Qualité premium, testé en laboratoire.",
    shortDescription:
      "Le 'cannabinoïde du sommeil' à son potentiel maximum. Une huile riche en CBN conçue spécifiquement pour ceux qui se réveillent en pleine nuit.",
    benefits: [
      "Lutte contre les réveils nocturnes",
      "Relaxation musculaire profonde",
      "Effet sédatif naturel puissant",
    ],
    composition: [
      "Huile MCT Bio",
      "Isolat de CBN (10%)",
      "Extrait CBD Broad Spectrum",
      "Terpènes de Lavande",
    ],
    usageTips:
      "Réservé à l'adulte. 2 à 4 gouttes sous la langue au moment du coucher. Ne pas conduire après prise.",
    labCertificate: "/certificates/w4-analysis.pdf",
    origin: "france",
    images: [
      "/images/products/bien_etre/huile-cbn-nuit-profonde.webp",
      "/images/products/bien_etre/baume-arthrose-cbd.webp",
    ],
  },
  {
    id: "w3",
    name: "Gummies Mélatonine & CBD",
    category: "Comestibles",
    price: 29.9,
    image: "/images/products/bien_etre/baume-arthrose-cbd.webp",
    tags: ["Sommeil"],
    isHot: true,
    universe: "wellness",
    stock: 40,
    molecule: "CBD",
    capacity: "30 unités",
    concentrationDisplay: "25mg/u",
    vibe: "Un moment de douceur pour un lâcher-prise total.",
    profil: "Gummies vegan à la mélatonine, sans sucres raffinés.",
    gout: "Parfum fruité mûre & framboise sauvage.",
    origin: "france",
    images: [
      "/images/products/bien_etre/baume-arthrose-cbd.webp",
      "/images/products/bien_etre/gummies-cbd-sommeil.webp",
    ],
  },
  {
    id: "w16",
    name: "Tisane Nuit Étoilée Bio",
    category: "Bien-être",
    price: 12.9,
    image: "/images/products/bien_etre/patch-cbd-douleurs.webp",
    tags: ["Sommeil"],
    universe: "wellness",
    stock: 80,
    molecule: "CBD",
    origin: "france",
  },
  {
    id: "w17",
    name: "Spray Buccal Sommeil Flash",
    category: "Bien-être",
    price: 24.9,
    image: "/images/products/bien_etre/huile-cbg-focus.webp",
    tags: ["Sommeil"],
    universe: "wellness",
    stock: 30,
    molecule: "CBN",
    origin: "france",
  },
  {
    id: "w18",
    name: "Gélules CBN Sérénité",
    category: "Gélules",
    price: 39.0,
    image: "/images/products/bien_etre/infusion-cbd-relaxation.webp",
    tags: ["Sommeil"],
    universe: "wellness",
    stock: 25,
    molecule: "CBN",
    capacity: "30 gélules",
    concentrationDisplay: "25mg/u",
    totalConcentration: "750mg",
    vibe: "Un sommeil sans accroc, une sérénité retrouvée.",
    profil: "Dose précise de CBN pur pour une efficacité constante.",
    gout: "Neutre, sans arôme.",
    origin: "france",
  },
  {
    id: "w19",
    name: "Infusion Valériane & CBD",
    category: "Bien-être",
    price: 14.5,
    image: "/images/products/bien_etre/gummies-cbd-sommeil.webp",
    tags: ["Sommeil"],
    universe: "wellness",
    stock: 45,
    molecule: "CBD",
    origin: "france",
  },
  {
    id: "w20",
    name: "Huile Sommeil Récup",
    category: "Huiles",
    price: 79.9,
    image: "/images/products/bien_etre/huile-cbd-sommeil.webp",
    tags: ["Sommeil"],
    isTeamChoice: true,
    universe: "wellness",
    stock: 12,
    molecule: "CBD",
    origin: "france",
  },
  {
    id: "w2",
    name: "Amnesia Haze Bio",
    category: "Fleurs",
    price: 12.5,
    image: "/images/products/bien_etre/huile-cbn-nuit-profonde.webp",
    tags: ["Relaxation"],
    isNew: true,
    universe: "wellness",
    stock: 25,
    molecule: "CBD",
    origin: "holland",
    vibe: "Énergie créative et relaxation mentale harmonieuse.",
    profil: "Fleur Indoor Bio à haute teneur en terpènes naturels.",
    gout: "Palette d'agrumes explosives avec un final poivré.",
    capacity: "5g",
    concentrationDisplay: "12% CBD",
    metaTitle: "Fleur CBD Amnesia Haze Bio | Puissante & Citronnée - Gardenz",
    metaDescription:
      "La légende Amnesia Haze en version CBD légale. Culture Bio Indoor, arômes citronnés puissants. Livraison discrète en 24h.",
    shortDescription:
      "Une légende revisitée. Cultivée en Indoor avec amour, cette Amnesia offre des notes d'agrumes explosives et une relaxation mentale immédiate.",
    benefits: [
      "Culture Indoor Bio certifiée",
      "Arômes intenses (Terpènes naturels)",
      "Effet 'Good Vibes' instantané",
    ],
    composition: [
      "Fleurs de chanvre séchées (Cannabis Sativa L.)",
      "CBD : 12%",
      "THC < 0.3%",
    ],
    usageTips:
      "Idéale en vaporisation à 180°C pour profiter de tous les terpènes. Peut aussi s'infuser avec un corps gras.",
    labCertificate: "/certificates/w2-analysis.pdf",
    images: [
      "/images/products/bien_etre/huile-cbn-nuit-profonde.webp",
      "/images/products/bien_etre/baume-arthrose-cbd.webp",
    ],
    tieredPrices: [
      { amount: 5, unit: "g", price: 12.5, label: "Découverte" },
      {
        amount: 10,
        unit: "g",
        price: 22.0,
        label: "Populaire",
        discountBadge: "Top",
      },
      { amount: 20, unit: "g", price: 40.0, label: "Avantage" },
      {
        amount: 50,
        unit: "g",
        price: 90.0,
        label: "Économique",
        discountBadge: "Éco",
      },
    ],
  },
  {
    id: "w5",
    name: "Vape Pen Focus Menthe",
    category: "Vape",
    price: 34.9,
    image: "/images/products/bien_etre/huile-cbg-focus.webp",
    tags: ["Focus"],
    universe: "wellness",
    stock: 22,
    molecule: "CBG",
    origin: "france",
  },
  {
    id: "w6",
    name: "Baume Sport Récupération",
    category: "Cosmétique",
    price: 39.0,
    image: "/images/products/bien_etre/creme-cbd-recuperation.webp",
    tags: ["Relaxation"],
    universe: "wellness",
    stock: 30,
    molecule: "CBD",
    origin: "france",
    capacity: "50ml",
  },
  {
    id: "w7",
    name: "Infusion Zen Bio",
    category: "Bien-être",
    price: 14.9,
    image: "/images/products/bien_etre/creme-cbd-recuperation.webp",
    tags: ["Stress"],
    universe: "wellness",
    stock: 100,
    molecule: "CBD",
    origin: "france",
  },
  {
    id: "w8",
    name: "Orange Bud Indoor",
    category: "Fleurs",
    price: 11.0,
    image: "/images/products/bien_etre/huile-cbg-focus.webp",
    tags: ["Relaxation"],
    universe: "wellness",
    stock: 18,
    molecule: "CBD",
    origin: "france",
    tieredPrices: [
      { amount: 5, unit: "g", price: 11.0, label: "Starter" },
      {
        amount: 10,
        unit: "g",
        price: 19.8,
        label: "Medium",
        discountBadge: "Top",
      },
      { amount: 20, unit: "g", price: 35.0, label: "Eco" },
      {
        amount: 50,
        unit: "g",
        price: 77.0,
        label: "Max Pack",
        discountBadge: "Éco",
      },
    ],
  },
  {
    id: "w9",
    name: "Huile CBG Énergie",
    category: "Huiles",
    price: 54.9,
    image: "/images/products/bien_etre/infusion-cbd-relaxation.webp",
    tags: ["Focus"],
    universe: "wellness",
    stock: 12,
    molecule: "CBG",
    origin: "france",
  },
  {
    id: "w10",
    name: "Pastilles Menthe CBD",
    category: "Comestibles",
    price: 9.9,
    image: "/images/products/bien_etre/serum-cbd-visage.webp",
    tags: ["Stress"],
    universe: "wellness",
    stock: 60,
    molecule: "CBD",
    origin: "france",
  },
  {
    id: "w11",
    name: "Spray Sublingual Flash",
    category: "Bien-être",
    price: 24.9,
    image: "/images/products/bien_etre/huile-cbd-sommeil.webp",
    tags: ["Stress"],
    universe: "wellness",
    stock: 45,
    molecule: "CBD",
    capacity: "20ml",
    concentrationDisplay: "500mg CBD",
    vibe: "Effet immédiat en cas de pic de stress.",
    profil: "Absorption sublinguale ultra-rapide.",
    gout: "Menthe fraîche intense.",
    origin: "france",
    images: [
      "/images/products/bien_etre/huile-cbd-sommeil.webp",
      "/images/products/bien_etre/huile-cbg-focus.webp",
    ],
  },
  {
    id: "w12",
    name: "Gélules Immunité CBD",
    category: "Gélules",
    price: 35.0,
    image: "/images/products/bien_etre/huile-cbn-nuit-profonde.webp",
    tags: ["Focus"],
    universe: "wellness",
    stock: 20,
    molecule: "CBD",
    capacity: "30 gélules",
    concentrationDisplay: "20mg/u",
    totalConcentration: "600mg",
    vibe: "Un bouclier naturel pour votre système immunitaire.",
    profil: "Formulation enrichie en vitamines et CBD à large spectre.",
    gout: "Neutre.",
    origin: "france",
  },
  {
    id: "w13",
    name: "Fleurs Straw-Haze Bio",
    category: "Fleurs",
    price: 10.5,
    image: "/images/products/bien_etre/creme-cbd-recuperation.webp",
    tags: ["Stress"],
    universe: "wellness",
    stock: 35,
    molecule: "CBD",
    origin: "france",
    tieredPrices: [
      { amount: 5, unit: "g", price: 10.5, label: "Découverte" },
      { amount: 10, unit: "g", price: 18.9, label: "Duo" },
      { amount: 20, unit: "g", price: 33.6, label: "Vibe" },
      {
        amount: 50,
        unit: "g",
        price: 73.5,
        label: "Bulk",
        discountBadge: "Éco",
      },
    ],
  },
  {
    id: "w14",
    name: "Huile de Massage Zen",
    category: "Cosmétique",
    price: 42.0,
    image: "/images/products/bien_etre/serum-cbd-visage.webp",
    tags: ["Relaxation"],
    universe: "wellness",
    stock: 15,
    molecule: "CBD",
    origin: "france",
    capacity: "100ml",
  },
  {
    id: "w15",
    name: "Boisson Gazéifiée CBD",
    category: "Boissons",
    price: 4.5,
    image: "/images/products/bien_etre/huile-cbg-focus.webp",
    tags: ["Focus"],
    universe: "wellness",
    stock: 120,
    molecule: "CBD",
    origin: "france",
  },
  // --- Nouveautés Out of Stock Wellness ---
  {
    id: "w21",
    name: "Baume Lèvres Chanvre & Karité",
    category: "Cosmétique",
    price: 8.9,
    image: "/images/products/bien_etre/infusion-cbd-relaxation.webp",
    tags: ["Relaxation"],
    universe: "wellness",
    stock: 0,
    molecule: "CBD",
    origin: "france",
    capacity: "15ml",
  },
  {
    id: "w22",
    name: "Tisane Détox Hiver",
    category: "Bien-être",
    price: 14.9,
    image: "/images/products/bien_etre/serum-cbd-visage.webp",
    tags: ["Focus"],
    universe: "wellness",
    stock: 0,
    molecule: "CBD",
    origin: "france",
  },
  {
    id: "w23",
    name: "Huile CBD Kids (Formule Douce)",
    category: "Huiles",
    price: 34.9,
    image: "/images/products/bien_etre/huile-cbd-sommeil.webp",
    tags: ["Stress"],
    universe: "wellness",
    stock: 0,
    molecule: "CBD",
    origin: "france",
  },
  // --- Nouveaux Produits (Enrichissement) ---
  {
    id: "w24",
    name: "Huile Routine Détente",
    category: "Huiles",
    price: 45.0,
    image: "/images/products/bien_etre/huile-cbn-nuit-profonde.webp",
    tags: ["Relaxation"],
    universe: "wellness",
    stock: 40,
    molecule: "CBD",
    origin: "france",
  },
  {
    id: "w25",
    name: "Huile Stop Stress",
    category: "Huiles",
    price: 55.0,
    image: "/images/products/bien_etre/creme-cbd-recuperation.webp",
    tags: ["Stress"],
    universe: "wellness",
    stock: 35,
    molecule: "CBD",
    origin: "france",
  },
  {
    id: "w26",
    name: "Gummies Boost Focus",
    category: "Comestibles",
    price: 29.0,
    image: "/images/products/bien_etre/huile-cbg-focus.webp",
    tags: ["Focus"],
    universe: "wellness",
    stock: 50,
    molecule: "CBD",
    origin: "france",
  },
  {
    id: "w27",
    name: "Chocolat Cacao Zen",
    category: "Comestibles",
    price: 15.0,
    image: "/images/products/bien_etre/infusion-cbd-relaxation.webp",
    tags: ["Relaxation"],
    universe: "wellness",
    stock: 60,
    molecule: "CBD",
    origin: "france",
  },
  {
    id: "w28",
    name: "Fleur Deep Sleep CBN",
    category: "Fleurs",
    price: 14.0,
    image: "/images/products/bien_etre/serum-cbd-visage.webp",
    tags: ["Sommeil"],
    universe: "wellness",
    stock: 30,
    molecule: "CBN",
    origin: "france",
    tieredPrices: [
      { amount: 5, unit: "g", price: 14.0, label: "Nuit" },
      { amount: 10, unit: "g", price: 25.0, label: "Semaine" },
      {
        amount: 20,
        unit: "g",
        price: 44.8,
        label: "Mois",
        discountBadge: "Top",
      },
      {
        amount: 50,
        unit: "g",
        price: 98.0,
        label: "Cure",
        discountBadge: "Éco",
      },
    ],
  },
  {
    id: "w29",
    name: "Fleur Lemon Haze CBG",
    category: "Fleurs",
    price: 13.0,
    image: "/images/products/bien_etre/huile-cbd-sommeil.webp",
    tags: ["Focus"],
    universe: "wellness",
    stock: 25,
    molecule: "CBG",
    origin: "italy",
    tieredPrices: [
      { amount: 5, unit: "g", price: 13.0, label: "Punch" },
      {
        amount: 10,
        unit: "g",
        price: 23.4,
        label: "Focus",
        discountBadge: "Top",
      },
      { amount: 20, unit: "g", price: 41.6, label: "Pro" },
      {
        amount: 50,
        unit: "g",
        price: 91.0,
        label: "Master",
        discountBadge: "Éco",
      },
    ],
  },
  {
    id: "w30",
    name: "Vape Night Rider",
    category: "Vape",
    price: 39.9,
    image: "/images/products/bien_etre/huile-cbn-nuit-profonde.webp",
    tags: ["Sommeil"],
    universe: "wellness",
    stock: 20,
    molecule: "CBN",
    origin: "france",
  },
  {
    id: "w31",
    name: "Vape Keep Cool",
    category: "Vape",
    price: 34.9,
    image: "/images/products/bien_etre/creme-cbd-recuperation.webp",
    tags: ["Stress"],
    universe: "wellness",
    stock: 25,
    molecule: "CBD",
    origin: "france",
  },
];

// --- EXTREME LAB (37 Produits) ---
export const EXTREME_PRODUCTS: Product[] = [
  // --- HARDCORE ---
  {
    id: "e1",
    name: "Moonrock Ice",
    category: "Concentrés",
    price: 25.0,
    image: "/images/products/extreme_lab/Whisk_4utm1cdz1qtzkhdotywowewlxazy00yyhdjntgd.webp",
    tags: ["Puissant"],
    isHot: true,
    intensity: "Hardcore",
    universe: "extreme",
    stock: 4,
    molecule: "THCP",
    origin: "usa",
    images: [
      "/images/products/extreme_lab/vape-jetable-hhc.webp",
      "/images/products/extreme_lab/moonrock-hhcp-o-purple.webp",
    ],
  },
  {
    id: "e2",
    name: "Diamonds THCP Pur",
    category: "Concentrés",
    price: 65.0,
    image: "/images/products/extreme_lab/vape-hhc-berry-blast.webp",
    tags: ["Cristal"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 15,
    molecule: "THCP",
    origin: "usa",
    images: [
      "/images/products/extreme_lab/vape-hhc-berry-blast.webp",
      "/images/products/extreme_lab/wax-thcp-gold.webp",
    ],
  },
  {
    id: "e4",
    name: "Shatter HHC-P Gold",
    category: "Concentrés",
    price: 45.0,
    image: "/images/products/extreme_lab/gummies-thcp-tropical.webp",
    tags: ["Intense"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 8,
    molecule: "HHC-P",
    origin: "usa",
    images: [
      "/images/products/extreme_lab/gummies-thcp-tropical.webp",
      "/images/products/extreme_lab/vape-hhc-p-mango.webp",
    ],
  },
  {
    id: "e7",
    name: "Huile Full Force",
    category: "Huiles",
    price: 89.0,
    image: "/images/products/extreme_lab/vape-h4cbd-ice.webp",
    tags: ["Elite"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 10,
    molecule: "CBD",
    origin: "france",
    images: [
      "/images/products/extreme_lab/vape-h4cbd-ice.webp",
      "/images/products/extreme_lab/resine-thch-dark.webp",
    ],
  },
  {
    id: "e9",
    name: "Crumble Pureté",
    category: "Concentrés",
    price: 40.0,
    image: "/images/products/extreme_lab/concentre-hhcp-o-hardcore.webp",
    tags: ["Lab"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 14,
    molecule: "H4-CBD",
    origin: "usa",
  },
  {
    id: "e11",
    name: "Icerock Blue",
    category: "Concentrés",
    price: 28.0,
    image: "/images/products/extreme_lab/wax-thcp-gold.webp",
    tags: ["Givré"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 12,
    molecule: "THCP",
    origin: "usa",
  },
  {
    id: "e15",
    name: "Triple Filtered THCP",
    category: "Résines",
    price: 22.0,
    image: "/images/products/extreme_lab/moonrock-hhcp-o-purple.webp",
    tags: ["Pur"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 30,
    molecule: "THCP",
    origin: "france",
  },
  {
    id: "e23",
    name: "Alien Kush HHCP-O",
    category: "Fleurs",
    price: 19.5,
    image: "/images/products/extreme_lab/vape-hhc-berry-blast.webp",
    tags: ["Spatial"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 10,
    molecule: "HHCP-O",
    origin: "holland",
    tieredPrices: [
      { amount: 5, unit: "g", price: 19.5, label: "Mission" },
      {
        amount: 10,
        unit: "g",
        price: 34.0,
        label: "Orbit",
        discountBadge: "Top",
      },
      { amount: 20, unit: "g", price: 62.0, label: "Galaxy" },
      {
        amount: 50,
        unit: "g",
        price: 135.0,
        label: "Universe",
        discountBadge: "Éco",
      },
    ],
  },
  {
    id: "e26",
    name: "Pod Extreme THCP 95%",
    category: "Vape",
    price: 54.9,
    image: "/images/products/extreme_lab/vape-hhc-berry-blast.webp",
    tags: ["Elite"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 20,
    molecule: "THCP",
    origin: "usa",
  },
  {
    id: "e29",
    name: "Gélules Lab Overdose",
    category: "Gélules",
    price: 65.0,
    image: "/images/products/extreme_lab/gummies-thcp-tropical.webp",
    tags: ["Puissant"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 12,
    molecule: "THCP",
    origin: "usa",
  },
  {
    id: "e32",
    name: "Double Zero THCB",
    category: "Résines",
    price: 24.0,
    image: "/images/products/extreme_lab/vape-h4cbd-ice.webp",
    tags: ["Légende"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 15,
    molecule: "THCB",
    origin: "holland",
  },
  {
    id: "e39",
    name: "Brownies Cosmic Trip",
    category: "Comestibles",
    price: 45.0,
    image: "/images/products/extreme_lab/concentre-hhcp-o-hardcore.webp",
    tags: ["Voyage"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 10,
    molecule: "THCP",
    origin: "usa",
  },
  // --- Nouveautés Out of Stock Extreme ---
  {
    id: "e35",
    name: "Moonrock Black Gold",
    category: "Concentrés",
    price: 35.0,
    image: "/images/products/extreme_lab/resine-thch-dark.webp",
    tags: ["Elite"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 0,
    molecule: "THCP",
    origin: "france",
  },
  {
    id: "e36",
    name: "Vape Live Resin THCP",
    category: "Vape",
    price: 49.9,
    image: "/images/products/extreme_lab/vape-hhc-p-mango.webp",
    tags: ["Vibe"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 0,
    molecule: "THCP",
    origin: "usa",
  },
  {
    id: "e37",
    name: "Edibles Turbo-Gummies",
    category: "Comestibles",
    price: 39.9,
    image: "/images/products/extreme_lab/vape-hhc-berry-blast.webp",
    tags: ["Snack"],
    intensity: "Medium",
    universe: "extreme",
    stock: 0,
    molecule: "HHC-P",
    origin: "usa",
  },
  {
    id: "e38",
    name: "Shatter Iridium Lab",
    category: "Concentrés",
    price: 55.0,
    image: "/images/products/extreme_lab/gummies-thcp-tropical.webp",
    tags: ["Puissant"],
    intensity: "Hardcore",
    universe: "extreme",
    stock: 0,
    molecule: "THCH",
    origin: "usa",
  },

  // --- MEDIUM ---
  {
    id: "e3",
    name: "Gummies Delta-9 Limit",
    category: "Comestibles",
    price: 35.0,
    image: "/images/products/extreme_lab/gummies-thcp-tropical.webp",
    tags: ["Euphorie"],
    intensity: "Medium",
    universe: "extreme",
    stock: 20,
    molecule: "Delta-9-THC",
    origin: "usa",
    images: [
      "/images/products/extreme_lab/gummies-thcp-tropical.webp",
      "/images/products/extreme_lab/concentre-hhcp-o-hardcore.webp",
    ],
  },
  {
    id: "e5",
    name: "Vape Cartridge HHCP-O",
    category: "Vape",
    price: 39.9,
    image: "/images/products/extreme_lab/vape-h4cbd-ice.webp",
    tags: ["Vibe"],
    intensity: "Medium",
    universe: "extreme",
    stock: 30,
    molecule: "HHCP-O",
    origin: "usa",
  },
  {
    id: "e6",
    name: "Hash Lebanais THCP",
    category: "Résines",
    price: 18.0,
    image: "/images/products/extreme_lab/vape-h4cbd-ice.webp",
    tags: ["Tradition"],
    intensity: "Medium",
    universe: "extreme",
    stock: 50,
    molecule: "THCP",
    origin: "france",
  },
  {
    id: "e10",
    name: "Vape Pen Jetable THCH",
    category: "Vape",
    price: 29.9,
    image: "/images/products/extreme_lab/vape-hhc-p-mango.webp",
    tags: ["Flash"],
    intensity: "Medium",
    universe: "extreme",
    stock: 40,
    molecule: "THCH",
    origin: "usa",
  },
  {
    id: "e12",
    name: "Gélules High-Potency",
    category: "Gélules",
    price: 49.0,
    image: "/images/products/extreme_lab/concentre-hhcp-o-hardcore.webp",
    tags: ["Discret"],
    intensity: "Medium",
    universe: "extreme",
    stock: 25,
    molecule: "HHC-P",
    origin: "usa",
  },
  {
    id: "e13",
    name: "Gorilla Glue THCP",
    category: "Fleurs",
    price: 16.0,
    image: "/images/products/extreme_lab/resine-thch-dark.webp",
    tags: ["Puissant"],
    intensity: "Medium",
    universe: "extreme",
    stock: 18,
    molecule: "THCP",
    origin: "italy",
    tieredPrices: [
      { amount: 5, unit: "g", price: 16.0, label: "Standard" },
      {
        amount: 10,
        unit: "g",
        price: 28.0,
        label: "Medium",
        discountBadge: "Top",
      },
      { amount: 20, unit: "g", price: 50.0, label: "Large" },
      {
        amount: 50,
        unit: "g",
        price: 110.0,
        label: "XL Pack",
        discountBadge: "Éco",
      },
    ],
  },
  {
    id: "e16",
    name: "Resine Afghan Medium",
    category: "Résines",
    price: 14.0,
    image: "/images/products/extreme_lab/vape-hhc-p-mango.webp",
    tags: ["Classic"],
    intensity: "Medium",
    universe: "extreme",
    stock: 30,
    molecule: "HHC",
    origin: "france",
  },
  {
    id: "e24",
    name: "Huile Focus THCV",
    category: "Huiles",
    price: 59.0,
    image: "/images/products/extreme_lab/resine-thch-dark.webp",
    tags: ["Énergie"],
    intensity: "Medium",
    universe: "extreme",
    stock: 22,
    molecule: "THCV",
    origin: "france",
  },
  {
    id: "e27",
    name: "Purple Haze THCH",
    category: "Fleurs",
    price: 14.5,
    image: "/images/products/extreme_lab/vape-hhc-berry-blast.webp",
    tags: ["Vibe"],
    intensity: "Medium",
    universe: "extreme",
    stock: 25,
    molecule: "THCH",
    origin: "france",
    tieredPrices: [
      { amount: 5, unit: "g", price: 14.5, label: "Classic" },
      {
        amount: 10,
        unit: "g",
        price: 26.0,
        label: "Duo",
        discountBadge: "Top",
      },
      { amount: 20, unit: "g", price: 46.4, label: "Squad" },
      {
        amount: 50,
        unit: "g",
        price: 101.5,
        label: "Party",
        discountBadge: "Éco",
      },
    ],
  },
  {
    id: "e30",
    name: "HHCA Wax Medium",
    category: "Concentrés",
    price: 38.0,
    image: "/images/products/extreme_lab/gummies-thcp-tropical.webp",
    tags: ["Texture"],
    intensity: "Medium",
    universe: "extreme",
    stock: 18,
    molecule: "HHCA",
    origin: "usa",
  },
  {
    id: "e33",
    name: "Space Cookies HHCP",
    category: "Comestibles",
    price: 29.9,
    image: "/images/products/extreme_lab/vape-h4cbd-ice.webp",
    tags: ["Snack"],
    intensity: "Medium",
    universe: "extreme",
    stock: 40,
    molecule: "HHC-P",
    origin: "holland",
  },

  // --- SOFT ---
  {
    id: "e8",
    name: "Gelato THCP Soft",
    category: "Fleurs",
    price: 15.0,
    image: "/images/products/extreme_lab/concentre-hhcp-o-hardcore.webp",
    tags: ["Saveur"],
    intensity: "Soft",
    universe: "extreme",
    stock: 22,
    molecule: "THCP",
    origin: "france",
    tieredPrices: [
      { amount: 5, unit: "g", price: 15.0, label: "Glace" },
      {
        amount: 10,
        unit: "g",
        price: 27.0,
        label: "Pot",
        discountBadge: "Top",
      },
      { amount: 20, unit: "g", price: 48.0, label: "Party" },
      {
        amount: 50,
        unit: "g",
        price: 105.0,
        label: "XL",
        discountBadge: "Éco",
      },
    ],
  },
  {
    id: "e17",
    name: "Huile H4-CBD",
    category: "Huiles",
    price: 34.0,
    image: "/images/products/extreme_lab/resine-thch-dark.webp",
    tags: ["Smooth"],
    intensity: "Soft",
    universe: "extreme",
    stock: 40,
    molecule: "H4-CBD",
    origin: "france",
  },
  {
    id: "e18",
    name: "Gummies Soft Kick",
    category: "Comestibles",
    price: 19.9,
    image: "/images/products/extreme_lab/vape-hhc-p-mango.webp",
    tags: ["Entrée"],
    intensity: "Soft",
    universe: "extreme",
    stock: 60,
    molecule: "CBD",
    origin: "usa",
  },
  {
    id: "e19",
    name: "Vape Pen Fruity Soft",
    category: "Vape",
    price: 24.9,
    image: "/images/products/extreme_lab/vape-hhc-berry-blast.webp",
    tags: ["Léger"],
    intensity: "Soft",
    universe: "extreme",
    stock: 35,
    molecule: "CBG",
    origin: "usa",
  },
  {
    id: "e20",
    name: "Fleurs White Widow Soft",
    category: "Fleurs",
    price: 9.5,
    image: "/images/products/extreme_lab/gummies-thcp-tropical.webp",
    tags: ["Débutant"],
    intensity: "Soft",
    universe: "extreme",
    stock: 50,
    molecule: "THCP",
    origin: "france",
    tieredPrices: [
      { amount: 5, unit: "g", price: 9.5, label: "Toile" },
      {
        amount: 10,
        unit: "g",
        price: 17.0,
        label: "Spider",
        discountBadge: "Top",
      },
      { amount: 20, unit: "g", price: 30.0, label: "Venom" },
      {
        amount: 50,
        unit: "g",
        price: 62.0,
        label: "Empire",
        discountBadge: "Éco",
      },
    ],
  },
  {
    id: "e21",
    name: "Resine Mousseuse Soft",
    category: "Résines",
    price: 10.0,
    image: "/images/products/extreme_lab/vape-h4cbd-ice.webp",
    tags: ["Chill"],
    intensity: "Soft",
    universe: "extreme",
    stock: 45,
    molecule: "CBD",
    origin: "france",
  },
  {
    id: "e22",
    name: "Spray Lab Soft Experience",
    category: "Gélules",
    price: 29.0,
    image: "/images/products/extreme_lab/concentre-hhcp-o-hardcore.webp",
    tags: ["Précis"],
    intensity: "Soft",
    universe: "extreme",
    stock: 20,
    molecule: "CBD",
    origin: "france",
  },
  {
    id: "e25",
    name: "H4-CBD Crumble Soft",
    category: "Concentrés",
    price: 32.0,
    image: "/images/products/extreme_lab/resine-thch-dark.webp",
    tags: ["Découverte"],
    intensity: "Soft",
    universe: "extreme",
    stock: 15,
    molecule: "H4-CBD",
    origin: "usa",
  },
  {
    id: "e28",
    name: "Hash Sommeil Soft",
    category: "Résines",
    price: 12.0,
    image: "/images/products/extreme_lab/vape-hhc-p-mango.webp",
    tags: ["Nuit"],
    intensity: "Soft",
    universe: "extreme",
    stock: 30,
    molecule: "CBN",
    origin: "france",
  },
  {
    id: "e31",
    name: "Vape Pen Daily H4",
    category: "Vape",
    price: 29.9,
    image: "/images/products/extreme_lab/vape-hhc-berry-blast.webp",
    tags: ["Daily"],
    intensity: "Soft",
    universe: "extreme",
    stock: 40,
    molecule: "H4-CBD",
    origin: "usa",
  },
  {
    id: "e34",
    name: "White CBG Soft",
    category: "Fleurs",
    price: 11.0,
    image: "/images/products/extreme_lab/gummies-thcp-tropical.webp",
    tags: ["Clarté"],
    intensity: "Soft",
    universe: "extreme",
    stock: 25,
    molecule: "CBG",
    origin: "italy",
    tieredPrices: [
      { amount: 5, unit: "g", price: 11.0, label: "Lumière" },
      {
        amount: 10,
        unit: "g",
        price: 19.8,
        label: "Rayon",
        discountBadge: "Top",
      },
      { amount: 20, unit: "g", price: 35.0, label: "Soleil" },
      {
        amount: 50,
        unit: "g",
        price: 77.0,
        label: "Éclat",
        discountBadge: "Éco",
      },
    ],
  },
];

// --- LIFESTYLE (18 Produits) ---
export const LIFESTYLE_PRODUCTS: Product[] = [
  {
    id: "l1",
    name: "Hoodie Gardenz Signature",
    category: "Vêtements / Hoodies",
    price: 65.0,
    image: "/images/products/lifestyle/Gemini_Generated_Image_6q13006q13006q13.webp",
    tags: ["Streetwear"],
    isNew: true,
    universe: "lifestyle",
    stock: 50,
    origin: "france",
  },
  {
    id: "l2",
    name: "Grinder Céramique Noir",
    category: "Accessoires",
    price: 49.9,
    image: "/images/products/lifestyle/grinder-premium-argent.webp",
    tags: ["Premium"],
    universe: "lifestyle",
    stock: 30,
    origin: "italy",
  },
  {
    id: "l3",
    name: "Vaporisateur Pax Plus",
    category: "Accessoires",
    price: 199.0,
    image: "/images/products/lifestyle/hoodie-gardenz-noir.webp",
    tags: ["High-Tech"],
    universe: "lifestyle",
    stock: 15,
    origin: "usa",
  },
  {
    id: "l4",
    name: "Livre : La Bible du Chanvre",
    category: "Livres",
    price: 25.0,
    image: "/images/products/lifestyle/Gemini_Generated_Image_lyw38klyw38klyw3.webp",
    tags: ["Culture"],
    universe: "lifestyle",
    stock: 100,
    origin: "france",
  },
  {
    id: "l5",
    name: "T-Shirt 'Molecular Vibe'",
    category: "Vêtements / T-shirts",
    price: 35.0,
    image: "/images/products/lifestyle/tshirt-lab-blanc.webp",
    tags: ["Streetwear"],
    universe: "lifestyle",
    stock: 80,
    origin: "france",
  },
  {
    id: "l6",
    name: "Vinyle Gardenz Sessions #1",
    category: "Musique",
    price: 30.0,
    image: "/images/products/lifestyle/casquette-gardenz-logo.webp",
    tags: ["Lo-Fi"],
    universe: "lifestyle",
    stock: 20,
    origin: "france",
  },
  {
    id: "l7",
    name: "Plateau de roulage Bambou",
    category: "Accessoires",
    price: 19.9,
    image: "/images/products/lifestyle/carnet-rolling-kit.webp",
    tags: ["Nature"],
    universe: "lifestyle",
    stock: 55,
    origin: "holland",
  },
  {
    id: "l8",
    name: "Sac à dos discret 'Anti-Odeur'",
    category: "Accessoires",
    price: 75.0,
    image: "/images/products/lifestyle/bag-gardenz-tote.webp",
    tags: ["Voyage"],
    universe: "lifestyle",
    stock: 12,
    origin: "usa",
  },
  {
    id: "l9",
    name: "Casquette Logo Brodé",
    category: "Vêtements / Accessoires",
    price: 29.0,
    image: "/images/products/lifestyle/Gemini_Generated_Image_q75qvuq75qvuq75q.webp",
    tags: ["Summer"],
    universe: "lifestyle",
    stock: 40,
    origin: "france",
  },
  {
    id: "l10",
    name: "Pack 12 Feuilles Slim Bio",
    category: "Accessoires",
    price: 15.0,
    image: "/images/products/lifestyle/grinder-premium-argent.webp",
    tags: ["Essentiel"],
    universe: "lifestyle",
    stock: 200,
    origin: "france",
  },
  {
    id: "l11",
    name: "Sweat à capuche 'Clan'",
    category: "Vêtements / Hoodies",
    price: 70.0,
    image: "/images/products/lifestyle/Whisk_1ugnlvwmifjnlvzytemnxewlxgjm00szkfjytkz.webp",
    tags: ["Limited"],
    isLimited: true,
    universe: "lifestyle",
    stock: 5,
    origin: "france",
  },
  {
    id: "l12",
    name: "Vinyle Gardenz Sessions #2",
    category: "Musique",
    price: 30.0,
    image: "/images/products/lifestyle/bag-gardenz-tote.webp",
    tags: ["Lo-Fi"],
    universe: "lifestyle",
    stock: 25,
    origin: "france",
  },
  {
    id: "l13",
    name: "Livre : Cuisine au CBD",
    category: "Livres",
    price: 22.0,
    image: "/images/products/lifestyle/hoodie-gardenz-noir.webp",
    tags: ["Guide"],
    universe: "lifestyle",
    stock: 80,
    origin: "france",
  },
  {
    id: "l14",
    name: "Gourde Isotherme Gardenz",
    category: "Accessoires",
    price: 25.0,
    image: "/images/products/lifestyle/gourde-isotherme-gardenz.webp",
    tags: ["Outdoor"],
    universe: "lifestyle",
    stock: 40,
    origin: "usa",
  },
  {
    id: "l15",
    name: "Short de compression Sport",
    category: "Vêtements",
    price: 45.0,
    image: "/images/products/lifestyle/plateau-bambou-rolling.webp",
    tags: ["Performance"],
    universe: "lifestyle",
    stock: 30,
    origin: "italy",
  },
  // --- Nouveautés Out of Stock Lifestyle ---
  {
    id: "l16",
    name: "Veste de Travail Gardenz",
    category: "Vêtements",
    price: 89.0,
    image: "/images/products/lifestyle/veste-workwear-gardenz.webp",
    tags: ["Limited"],
    universe: "lifestyle",
    stock: 0,
    origin: "france",
  },
  {
    id: "l17",
    name: "Kit de Nettoyage High-Tech",
    category: "Accessoires",
    price: 24.9,
    image: "/images/products/lifestyle/carnet-rolling-kit.webp",
    tags: ["Premium"],
    universe: "lifestyle",
    stock: 0,
    origin: "usa",
  },
  {
    id: "l18",
    name: "Vinyle Sessions #3 (Pre-order)",
    category: "Musique",
    price: 35.0,
    image: "/images/products/lifestyle/bag-gardenz-tote.webp",
    tags: ["Lo-Fi"],
    universe: "lifestyle",
    stock: 0,
    origin: "france",
  },
];

// --- AGGREGATIONS & ADDITIONAL DATA ---
export const ALL_PRODUCTS: Product[] = [
  ...WELLNESS_PRODUCTS,
  ...EXTREME_PRODUCTS,
  ...LIFESTYLE_PRODUCTS,
];

export const TOP_SELECTION: Product[] = [
  // Bien-être
  WELLNESS_PRODUCTS[0], // Huile CBD Sommeil
  WELLNESS_PRODUCTS[2], // Gummies Mélatonine
  WELLNESS_PRODUCTS[1], // Huile CBN Nuit Profonde
  WELLNESS_PRODUCTS[13], // Huile CBG Énergie
  WELLNESS_PRODUCTS[3], // Tisane Nuit Étoilée

  // eXtreme Lab
  EXTREME_PRODUCTS[0], // Moonrock Ice (Hardcore)
  EXTREME_PRODUCTS[1], // Diamonds THCP (Hardcore)
  EXTREME_PRODUCTS[7], // Alien Kush (Hardcore)
  EXTREME_PRODUCTS[8], // Pod Extreme (Hardcore)
  EXTREME_PRODUCTS[11], // Gummies Delta-9 (Medium)

  // LifeStyle
  LIFESTYLE_PRODUCTS[0], // Hoodie Signature
  LIFESTYLE_PRODUCTS[2], // Vaporisateur Pax Plus
  LIFESTYLE_PRODUCTS[4], // T-Shirt Molecular
  LIFESTYLE_PRODUCTS[10], // Sweat à capuche Clan
  LIFESTYLE_PRODUCTS[5], // Vinyle Session #1
];

export const REVIEWS: Review[] = [
  {
    id: "r1",
    author: "Marc D.",
    rating: 5,
    text: "L'huile Sommeil est incroyable, je ne m'en passe plus. Un vrai game changer pour mes nuits.",
    universe: "Bien-être",
    productCategory: "Huiles",
    image: "/images/products/lifestyle/hoodie-gardenz-noir.webp",
  },
  {
    id: "r2",
    author: "Sophie L.",
    rating: 4,
    text: "Le Moonrock est très puissant, attention au dosage. Mais le goût est fantastique.",
    universe: "eXtreme Lab",
    productCategory: "Concentrés",
    image: "/images/products/lifestyle/tshirt-lab-blanc.webp",
  },
  {
    id: "r3",
    author: "Thomas K.",
    rating: 5,
    text: "Super hoodie, la qualité du coton est top. Livraison très discrète comme promis.",
    universe: "Bien-être",
    productCategory: "Vêtements",
    image: "/images/products/lifestyle/casquette-gardenz-logo.webp",
  },
  {
    id: "r4",
    author: "Julie M.",
    rating: 5,
    text: "Les gummies au CBD m'aident énormément à gérer le stress au bureau sans somnolence.",
    universe: "Bien-être",
    productCategory: "Comestibles",
    image: "/images/products/lifestyle/grinder-premium-argent.webp",
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "b1",
    title: "Le CBN : La nouvelle frontière du sommeil",
    slug: "tout-savoir-sur-le-cbn",
    excerpt:
      "Découvrez pourquoi le CBN devient le compagnon de nuit favori de la communauté Gardenz.",
    content:
      "<p>Le CBN, ou cannabinol, est un cannabinoïde qui gagne en popularité pour ses effets relaxants...</p>",
    image: "/images/products/lifestyle/carnet-rolling-kit.webp",
    category: "Bien-être",
    author: "Dr. Green",
    date: "12 Mai 2025",
    readTime: "4 min",
    relatedProducts: ["w4", "w18"],
  },
  {
    id: "b2",
    title: "Comment choisir son vaporisateur en 2025 ?",
    slug: "guide-vaporisateurs-2025",
    excerpt:
      "Technologie, température, autonomie : on décrypte tout pour vous aider à choisir.",
    content:
      "<p>Vaporiser est souvent considéré comme une alternative plus saine à la combustion...</p>",
    image: "/images/products/lifestyle/bag-gardenz-tote.webp",
    category: "Guide",
    author: "Benjamin",
    date: "05 Mai 2025",
    readTime: "6 min",
    relatedProducts: ["l3"],
  },
  {
    id: "b3",
    title: "L'art du 'Dabbing' et les concentrés Lab",
    slug: "art-du-dabbing-concentres",
    excerpt:
      "Plongée dans l'univers eXtreme Lab : textures, saveurs et intensité pure.",
    content:
      "<p>Les concentrés représentent la forme la plus pure d'extraction des cannabinoïdes...</p>",
    image: "/images/products/lifestyle/hoodie-gardenz-noir.webp",
    category: "eXtreme Lab",
    author: "Clan Expert",
    date: "28 Avril 2025",
    readTime: "8 min",
    relatedProducts: ["e1", "e2", "e4"],
  },
  // --- NOUVEAUX ARTICLES : BIEN-ÊTRE ---
  {
    id: "b4",
    title: "CBD et Récupération Sportive : Ce que dit la Science",
    slug: "cbd-recuperation-sportive-science",
    excerpt:
      "Comment les athlètes intègrent-ils les cannabinoïdes dans leur routine post-entraînement ?",
    content:
      "<h2>L'inflammation, ennemie numéro 1 du sportif</h2><p>Après un effort intense, les micro-déchirures musculaires provoquent une inflammation... Le CBD, de par ses propriétés anti-inflammatoires potentielles, est de plus en plus plébiscité. <strong>Découvrez comment l'utiliser :</strong></p><ul><li>En application locale (Baume) directement sur la zone concernée.</li><li>En sublingual (Huile) pour une action globale sur la détente musculaire et nerveuse.</li></ul><p><em>Attention : Le CBD ne remplace pas l'échauffement ni l'hydratation.</em></p>",
    image: "/images/products/bien_etre/creme-cbd-recuperation.webp",
    category: "Bien-être",
    author: "Coach Alex",
    date: "14 Juin 2025",
    readTime: "5 min",
    relatedProducts: ["w6", "w14", "w25"],
  },
  {
    id: "b5",
    title: "Micro-dosage de CBD : Focus & Productivité au travail",
    slug: "micro-dosage-cbd-focus-productivite",
    excerpt:
      "Optimiser sa concentration sans subir de somnolence grâce au protocole du micro-dosage.",
    content:
      "<h2>Qu'est-ce que le micro-dosage ?</h2><p>Le micro-dosage consiste à prendre des quantités minimes de cannabinoïdes (comme le CBD ou le CBG) tout au long de la journée pour maintenir un niveau constant dans l'organisme sans provoquer d'effet de 'lourdeur'.</p><h3>Les avantages du CBG pour la concentration</h3><p>Souvent appelé le cannabinoïde de 'l'énergie mentale', le CBG, pris à faible dose, aide à canaliser le focus et atténuer les pics de stress liés à l'environnement professionnel.</p>",
    image: "/images/products/bien_etre/huile-cbg-focus.webp",
    category: "Bien-être",
    author: "Dr. Green",
    date: "02 Juillet 2025",
    readTime: "4 min",
    relatedProducts: ["w9", "w10", "w12"],
  },
  {
    id: "b6",
    title: "Mélatonine Naturelle vs Synthétique : Décryptage",
    slug: "melatonine-naturelle-vs-synthetique",
    excerpt:
      "Toutes les mélatonines ne se valent pas. Comprendre l'apport du spectre complet.",
    content:
      "<h2>Le piège de la Mélatonine de synthèse</h2><p>De nombreux compléments utilisent des formes chimiques de mélatonine. Bien qu'efficaces à court terme, elles peuvent perturber le cycle naturel.</p><h3>La synergie Botanique</h3><p>Combiner une mélatonine naturelle avec du CBN (le cannabinoïde du sommeil) et du CBD full-spectrum crée un <strong>effet d'entourage</strong> puissant. L'endormissement est facilité sans l'effet 'groggy' du lendemain matin.</p>",
    image: "/images/products/bien_etre/gummies-cbd-sommeil.webp",
    category: "Bien-être",
    author: "Dr. Sophie M.",
    date: "18 Juillet 2025",
    readTime: "6 min",
    relatedProducts: ["w1", "w3", "w28"],
  },

  // --- NOUVEAUX ARTICLES : EXTREME LAB ---
  {
    id: "b7",
    title: "Le THCP expliqué : Puissance et Précautions",
    slug: "thcp-explique-puissance-precautions",
    excerpt:
      "Plongée moléculaire dans l'un des cannabinoïdes les plus intenses de la galaxie eXtreme Lab.",
    content:
      "<h2>Une découverte moléculaire majeure</h2><p>Le THCP possède une chaîne latérale alkylée plus longue, ce qui lui confère une affinité décuplée avec le récepteur CB1 du système endocannabinoïde.</p><h3>Consignes de vol</h3><p>En raison de sa puissance, le THCP est <strong>strictement réservé aux utilisateurs très expérimentés</strong>. Nous recommandons de commencer par de micro-inhalations, d'attendre 20 minutes avant toute nouvelle prise, et de ne jamais consommer avant de conduire.</p>",
    image: "/images/products/extreme_lab/vape-hhc-berry-blast.webp",
    category: "eXtreme Lab",
    author: "Clan Expert",
    date: "05 Juin 2025",
    readTime: "7 min",
    relatedProducts: ["e1", "e2", "e13"],
  },
  {
    id: "b8",
    title: "Moonrock Ice : Les secrets de sa fabrication",
    slug: "moonrock-ice-fabrication-secrets",
    excerpt:
      "Découvrez les coulisses de la création des joyaux les plus givrés de notre collection.",
    content:
      "<h2>L'artisanat Extrême</h2><p>Un Moonrock Ice n'est pas une simple fleur. Il s'agit d'une superposition technique nécessitant plusieurs semaines d'élaboration.</p><ol><li><strong>Sélection du calice :</strong> Choisir une bud dense et résineuse.</li><li><strong>Infusion :</strong> Enrobage minutieux à l'huile pure de cannabinoïde.</li><li><strong>Cristallisation (Le givre) :</strong> Roulement dans des cristaux d'isolat purs pour créer la gangue glacée caractéristique.</li></ol>",
    image: "/images/products/extreme_lab/moonrock-hhcp-o-purple.webp",
    category: "eXtreme Lab",
    author: "Clan Expert",
    date: "22 Juin 2025",
    readTime: "4 min",
    relatedProducts: ["e1", "e11"],
  },
  {
    id: "b9",
    title: "H4-CBD vs CBD Classique : Ce qu'il faut savoir",
    slug: "h4cbd-vs-cbd-classique",
    excerpt:
      "L'alternative 'Soft' du labo : une relaxation amplifiée par hydrogénation.",
    content:
      "<h2>L'Hydrogénation au service du Chill</h2><p>Le H4-CBD est un dérivé synthétique obtenu en ajoutant 4 atomes d'hydrogène à la molécule de CBD. Ce processus, similaire à la fabrication de la margarine, augmente considérablement sa stabilité et son ressenti physique.</p><h3>Pour qui ?</h3><p>Il est idéal pour ceux qui trouvent le CBD trop léger, mais qui souhaitent éviter l'intensité psychoactive de la gamme Hardcore. L'effet est souvent décrit comme un profond relâchement corporel.</p>",
    image: "/images/products/extreme_lab/vape-h4cbd-ice.webp",
    category: "eXtreme Lab",
    author: "Clan Expert",
    date: "10 Aout 2025",
    readTime: "5 min",
    relatedProducts: ["e17", "e25", "e31"],
  },

  // --- NOUVEAUX ARTICLES : LIFESTYLE ---
  {
    id: "b10",
    title: "L'évolution du Streetwear : De l'underground à Gardenz",
    slug: "evolution-streetwear-gardenz",
    excerpt:
      "Comment les contre-cultures ont façonné notre collection de vêtements organiques.",
    content:
      "<h2>S'habiller en pleine conscience</h2><p>Le streetwear revendique l'appartenance à un clan, à une culture. Historiquement marginalisé, l'univers du chanvre dicte aujourd'hui les codes d'une mode responsable et affranchie.</p><h3>La Collection Signature</h3><p>Nos hoodies et t-shirts sont bien plus que des vêtements... ils sont conçus en coton 100% organique, garantissant durabilité, confort et absence d'exploitation environnementale. Portez vos idéaux.</p>",
    image: "/images/products/lifestyle/hoodie-gardenz-noir.webp",
    category: "Lifestyle",
    author: "Benjamin",
    date: "28 Mai 2025",
    readTime: "3 min",
    relatedProducts: ["l1", "l5", "l11"],
  },
  {
    id: "b11",
    title: "Playlist Gardenz Sessions : La Vibe Lo-Fi ultime",
    slug: "playlist-gardenz-sessions-lo-fi",
    excerpt:
      "Platines vinyl, chill steps et sessions nocturnes. La bande-son de vos dégustations.",
    content:
      "<h2>L'alliance des sens</h2><p>La dégustation est une expérience polysensorielle. Tout comme les terpènes activent vos récepteurs olfactifs, la musique Lo-Fi Hip Hop crée un ancrage émotionnel parfait pour se détendre.</p><p>Dans le Vinyle <strong>Gardenz Sessions #1</strong>, nous avons collaboré avec 8 beatmakers français pour retranscrire la sensation exacte ressentie avec notre Amnesia Haze ou notre Hash Lebanais.</p>",
    image: "/images/products/lifestyle/casquette-gardenz-logo.webp",
    category: "Lifestyle",
    author: "DJ Selecta",
    date: "20 Juin 2025",
    readTime: "3 min",
    relatedProducts: ["l6", "l12"],
  },
  {
    id: "b12",
    title: "Le Matériel Roulage Premium : Outils et Traditions",
    slug: "materiel-roulage-premium",
    excerpt:
      "Pourquoi le choix de la feuille et du grinder modifie totalement le profil aromatique.",
    content:
      "<h2>L'Outil fait l'artisan</h2><p>Une mauvaise feuille brûle trop vite et altère le goût par la combustion excessive du papier. Un mauvais grinder écrase les trichomes précieux au lieu de scinder le végétal.</p><h3>La sainte trinité du roulage</h3><ul><li><strong>Le Grinder Céramique :</strong> Évite les résidus toxiques des grinders plastiques bas de gamme.</li><li><strong>Feuilles non blanchies :</strong> Préserve la santé de vos voies respiratoires (Zéro Chlore).</li><li><strong>Plateau en Bambou :</strong> Évite le gaspillage des trichomes.</li></ul>",
    image: "/images/products/lifestyle/grinder-premium-argent.webp",
    category: "Lifestyle",
    author: "Benjamin",
    date: "14 Aout 2025",
    readTime: "5 min",
    relatedProducts: ["l2", "l7", "l10"],
  },

  // --- NOUVEAUX ARTICLES : CULTURE ---
  {
    id: "b13",
    title: "L'histoire des Terpènes : Le langage secret des plantes",
    slug: "histoire-terpenes-langage-plantes",
    excerpt:
      "Myrcène, Limonène, Pinène... Apprenez à décoder les arômes de vos fleurs.",
    content:
      "<h2>Que sont les Terpènes ?</h2><p>Derrière chaque odeur se cache une molécule défensive sécrétée par la plante. Ces huiles essentielles naturelles protègent la plante des prédateurs, mais attirent les pollinisateurs.</p><h3>Top 3 des profils aromatiques</h3><ul><li><strong>Myrcène :</strong> Arôme terreux, musqué (Mangue). Favorise la relaxation profonde (Indica vibe).</li><li><strong>Limonène :</strong> Citrus ultra-frais. Stimulant l'humeur, effet antistress.</li><li><strong>Pinène :</strong> Odeur de sapin. Effet énergisant et bronchodilatateur léger.</li></ul>",
    image: "/images/products/bien_etre/huile-cbn-nuit-profonde.webp",
    category: "Culture",
    author: "Dr. Green",
    date: "09 Mai 2025",
    readTime: "6 min",
    relatedProducts: ["w2", "w8"],
  },
  {
    id: "b14",
    title: "Indoor vs Outdoor : Le grand débat",
    slug: "culture-indoor-vs-outdoor-debat",
    excerpt:
      "Lumière artificielle ou soleil naturel ? Avantages et inconvénients des méthodes de culture.",
    content:
      "<h2>Le contrôle total de l'Indoor</h2><p>Cultiver en intérieur permet de contrôler 100% de l'environnement (Température, Hygrométrie, Spectre Lumineux). Le résultat : Des têtes ultra-compactes, résineuses et visuellement parfaites.</p><h2>L'empreinte de la Terre (Outdoor/Greenhouse)</h2><p>Une culture en pleine terre, baignée par les UV naturels du soleil, développe souvent des spectres de terpènes plus complexes, bien que les têtes soient moins denses. Plus écologique, c'est l'essence brute de la nature.",
    image: "/images/products/bien_etre/huile-cbg-focus.webp",
    category: "Culture",
    author: "Benjamin",
    date: "25 Juillet 2025",
    readTime: "5 min",
    relatedProducts: ["w2", "w13", "e20"],
  },
  {
    id: "b15",
    title: "Le système endocannabinoïde expliqué aux novices",
    slug: "systeme-endocannabinoide-explique",
    excerpt:
      "Découvrez l'incroyable réseau de récepteurs neurologiques caché dans votre propre corps.",
    content:
      "<h2>Le rôle des récepteurs CB1 et CB2</h2><p>Ce qu'il faut comprendre, c'est que notre corps produit lui-même ses propres 'cannabinoïdes' pour réguler l'équilibre intérieur (homéostasie) de l'humeur, appétit, et température.</p><ul><li><strong>Les récepteurs CB1</strong> pullulent dans le système nerveux central et le cerveau.</li><li><strong>Les récepteurs CB2</strong> sont localisés principalement dans le système immunitaire et la rate.</li></ul><p>Les phyto-cannabinoïdes végétaux viennent simplement 'mimer' les clés pour ouvrir ces mêmes serrures.</p>",
    image: "/images/products/lifestyle/carnet-rolling-kit.webp",
    category: "Culture",
    author: "Dr. Sophie M.",
    date: "01 Aout 2025",
    readTime: "7 min",
    relatedProducts: ["w12", "w7"],
  },

  // --- NOUVEAUX ARTICLES : GUIDE ---
  {
    id: "b16",
    title: "Guide complet pour infuser la résine ou les fleurs",
    slug: "guide-complet-infusion-fleurs-resines",
    excerpt:
      "L'art de la décarboxylation : pourquoi l'eau chaude ne suffit pas ?",
    content:
      "<h2>L'erreur du débutant : L'Eau pure</h2><p>Les cannabinoïdes sont lipophiles, c'est-à-dire qu'ils ne se dissolvent que dans les <strong>corps gras</strong>, pas dans l'eau !</p><h3>La marche à suivre :</h3><ol><li><strong>La Décarboxylation :</strong> Chauffez doucement la fleur effritée au four (110°C) pendant 30min pour activer les molécules (Transformer le CBDA inactif en CBD actif).</li><li><strong>Corps gras :</strong> Ajoutez du lait entier, du beurre végétal, ou du lait d'amande très gras dans votre casserole d'eau frémissante.</li><li><strong>Infusion :</strong> Laissez infuser 15 minutes, filtrez, savourez votre boisson réconfortante.</li></ol>",
    image: "/images/products/extreme_lab/resine-thch-dark.webp",
    category: "Guide",
    author: "Clan Expert",
    date: "11 Juin 2025",
    readTime: "4 min",
    relatedProducts: ["w16", "w19", "e16"],
  },
  {
    id: "b17",
    title: "Comment conserver ses huiles et extraits (Labs)",
    slug: "conservation-huiles-et-extraits-extreme",
    excerpt:
      "Lumière, chaleur, oxygène : protégez vos produits de la dégradation moléculaire.",
    content:
      "<h2>Les 3 ennemis des cannabinoïdes</h2><p>Un produit mal conservé, c'est un investissement perdu. Trois facteurs détruisent rapidement les terpènes et oxydent les cannabinoïdes.</p><ul><li><strong>La Lumière (Les UV) :</strong> C'est pourquoi toutes nos huiles sont dans des flacons ambrés ou opaques.</li><li><strong>La Chaleur :</strong> Conservez les Moonrocks, Résines et Crumbles au réfrigérateur dans un <em>silicone hermétique</em> pendant l'été.</li><li><strong>L'Oxygène :</strong> Refermez immédiatement et hermétiquement les pochons après utilisation. L'air oxyde la matière végétale et sèche les trichomes.</li></ul>",
    image: "/images/products/extreme_lab/wax-thcp-gold.webp",
    category: "Guide",
    author: "Clan Expert",
    date: "29 Aout 2025",
    readTime: "3 min",
    relatedProducts: ["e9", "e21"],
  },
  {
    id: "b18",
    title: "Dosing Précis : Les comestibles pour les nuls",
    slug: "guide-dosage-comestibles-edibles",
    excerpt:
      "Ne vous faites plus piéger par l'effet retard des Gummies et du Chocolat au chanvre.",
    content:
      "<h2>La Digestion : La clé de l'absorption</h2><p>La règle d'or lors de l'ingestion de gummies ou gélules est : <strong>La Patience</strong>. Contrairement au vapotage ou aux huiles sublinguales (action en 15-30 minutes), la digestion implique le passage par le foie (métabolisation pancréatique).</p><h3>Le Timing</h3><p>Attendez toujours un minimum absolu de <strong>90 minutes</strong> avant de reprendre quoi que ce soit si vous ne ressentez pas les effets initiaux d'un gummy. L'effet est plus long à monter, mais sa durée totale peut s'étaler sur 4 à 8 heures.</p>",
    image: "/images/products/bien_etre/gummies-cbd-sommeil.webp",
    category: "Guide",
    author: "Dr. Sophie M.",
    date: "04 Septembre 2025",
    readTime: "5 min",
    relatedProducts: ["w3", "w26", "e3"],
  },

  // --- LIVE GARDENZ SESSIONS ---
  {
    id: "b19",
    title: "Live Gardenz Session #32 — Luce Tolassy",
    slug: "live-gardenz-session-32-luce-tolassy",
    excerpt:
      "Trois morceaux bruts, une voix organique et une session intimiste qui transcende les genres. Découvrez Luce Tolassy en live exclusif.",
    content:
      `<h2>La Session qui a fait vibrer le Clan</h2>
<p>Pour cette 32ème Live Gardenz Session, nous avons invité <strong>Luce Tolassy</strong>, artiste originaire d'Orléans portée par une voix puissante mêlant reggae, soul et émotion brute. Trois titres, zéro filtre, une prise live.</p>

<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;border-radius:16px;margin:2rem 0;">
<iframe src="https://www.youtube.com/embed/2pJX9BusWtM" title="Luce Tolassy - Live Gardenz Session #32" style="position:absolute;top:0;left:0;width:100%;height:100%;border:0;" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen loading="lazy"></iframe>
</div>

<h3>🎵 Les Morceaux</h3>
<ul>
<li><strong>Sad Man</strong> — Une ouverture en demi-teinte, portée par des harmonies reggae lancinantes.</li>
<li><strong>Bloody Sunday</strong> — Le tempo monte. La voix se libère. Un cri engagé aux accents soul.</li>
<li><strong>Elle s'en ira</strong> — La clôture parfaite. Un morceau en français, intime et suspendu.</li>
</ul>

<h3>🎤 Qui est Luce Tolassy ?</h3>
<p>Chanteuse, auteure et compositrice, Luce Tolassy puise dans le reggae, la soul et la chanson française pour construire un univers musical profondément humain. Sa voix, à la fois douce et percutante, est de celles qu'on n'oublie pas après une session live.</p>

<h3>📲 Suivre Luce Tolassy</h3>
<ul>
<li>Instagram : <a href="https://www.instagram.com/etollasy" target="_blank" rel="noopener noreferrer" style="color:#22c55e;text-decoration:underline;">@etollasy</a></li>
</ul>

<h3>🎬 Crédits de la Session</h3>
<ul>
<li><strong>Son :</strong> <a href="https://www.instagram.com/tiwony_officiel" target="_blank" rel="noopener noreferrer" style="color:#22c55e;">@tiwony_officiel</a> & <a href="https://www.instagram.com/fromthebush" target="_blank" rel="noopener noreferrer" style="color:#22c55e;">@fromthebush</a></li>
<li><strong>Vidéo :</strong> <a href="https://www.instagram.com/alleyezonit" target="_blank" rel="noopener noreferrer" style="color:#22c55e;">@alleyezonit</a></li>
<li><strong>Mixage :</strong> <a href="https://www.instagram.com/guardian_house_music" target="_blank" rel="noopener noreferrer" style="color:#22c55e;">@guardian_house_music</a> & <a href="https://www.instagram.com/cisko_delgado" target="_blank" rel="noopener noreferrer" style="color:#22c55e;">@cisko_delgado</a></li>
</ul>

<h3>🌿 C'est quoi les Live Gardenz Sessions ?</h3>
<p>Les <strong>Live Gardenz Sessions</strong> sont bien plus qu'une série de vidéos. C'est un mouvement. Un espace où musique, culture et lifestyle se croisent autour de la communauté Gardenz. Chaque session met en lumière un artiste indépendant dans un format raw, authentique et sans playback.</p>
<p>Retrouvez toutes les sessions sur <a href="https://www.youtube.com/@livegardenzsession" target="_blank" rel="noopener noreferrer" style="color:#22c55e;text-decoration:underline;">notre chaîne YouTube</a>.</p>`,
    image: "https://img.youtube.com/vi/2pJX9BusWtM/maxresdefault.jpg",
    category: "Lifestyle",
    author: "Live Gardenz Session",
    date: "13 Février 2026",
    readTime: "3 min",
    relatedProducts: ["l1", "l5", "l6"],
  },
  {
    id: "b20",
    title: "Live Gardenz Session #30 — Fdy Phenomen",
    slug: "live-gardenz-session-30-fdy-phenomen",
    excerpt:
      "Rap brut, flow chirurgical. Fdy Phenomen lâche « Patate de Mike » et « Syndrome de l'imposteur » en une prise live sans filet.",
    content:
      `<h2>Le Rap au scalpel</h2>
<p>Pour la 30ème Live Gardenz Session, c'est <strong>Fdy Phenomen</strong> qui prend le micro. Deux titres, un flow millimétré, et une énergie raw qui ne triche pas. Le format Gardenz révèle les artistes tels qu'ils sont : sans playback, sans retouche.</p>

<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;border-radius:16px;margin:2rem 0;">
<iframe src="https://www.youtube.com/embed/-RXVgzJsKQw" title="Fdy Phenomen - Live Gardenz Session #30" style="position:absolute;top:0;left:0;width:100%;height:100%;border:0;" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen loading="lazy"></iframe>
</div>

<h3>🎵 Les Morceaux</h3>
<ul>
<li><strong>Patate de Mike</strong> — Un track percutant, porté par des punchlines acérées et un beat lourd.</li>
<li><strong>Syndrome de l'imposteur</strong> — L'introspection prend le dessus. Un texte profond sur le doute et la légitimité.</li>
</ul>

<h3>🎤 Qui est Fdy Phenomen ?</h3>
<p>MC au flow incisif, Fdy Phenomen navigue entre rap conscient et egotrip avec une aisance rare. Chaque texte est ciselé, chaque live est une démonstration de maîtrise technique et d'authenticité.</p>

<h3>📲 Suivre Fdy Phenomen</h3>
<ul>
<li>Instagram : <a href="https://www.instagram.com/fdyphenomen" target="_blank" rel="noopener noreferrer" style="color:#22c55e;text-decoration:underline;">@fdyphenomen</a></li>
<li>Spotify : <a href="https://open.spotify.com/artist/0kP4W1fV8kK6KxJjLzQp0S" target="_blank" rel="noopener noreferrer" style="color:#22c55e;text-decoration:underline;">Fdy Phenomen sur Spotify</a></li>
<li>YouTube : <a href="https://www.youtube.com/@FDYPhenomen" target="_blank" rel="noopener noreferrer" style="color:#22c55e;text-decoration:underline;">@FDYPhenomen</a></li>
</ul>

<h3>🎬 Crédits de la Session</h3>
<ul>
<li><strong>Son :</strong> <a href="https://www.instagram.com/tiwony_officiel" target="_blank" rel="noopener noreferrer" style="color:#22c55e;">@tiwony_officiel</a></li>
<li><strong>Vidéo :</strong> <a href="https://www.instagram.com/alleyezonit" target="_blank" rel="noopener noreferrer" style="color:#22c55e;">@alleyezonit</a></li>
<li><strong>Mixage :</strong> <a href="https://www.instagram.com/guardian_house_music" target="_blank" rel="noopener noreferrer" style="color:#22c55e;">@guardian_house_music</a> & <a href="https://www.instagram.com/cisko_delgado" target="_blank" rel="noopener noreferrer" style="color:#22c55e;">@cisko_delgado</a></li>
</ul>

<h3>🌿 C'est quoi les Live Gardenz Sessions ?</h3>
<p>Les <strong>Live Gardenz Sessions</strong> sont bien plus qu'une série de vidéos. C'est un mouvement. Un espace où musique, culture et lifestyle se croisent autour de la communauté Gardenz. Chaque session met en lumière un artiste indépendant dans un format raw, authentique et sans playback.</p>
<p>Retrouvez toutes les sessions sur <a href="https://www.youtube.com/@livegardenzsession" target="_blank" rel="noopener noreferrer" style="color:#22c55e;text-decoration:underline;">notre chaîne YouTube</a>.</p>`,
    image: "https://img.youtube.com/vi/-RXVgzJsKQw/maxresdefault.jpg",
    category: "Lifestyle",
    author: "Live Gardenz Session",
    date: "16 Janvier 2026",
    readTime: "3 min",
    relatedProducts: ["l1", "l5", "l11"],
  },
];

// HMR trigger
